---
title: "p8105_hw5_zj2379"
author: "Zheshu Jiang"
date: "2023-11-12"
output: github_document
---

## Problem 1
```{r}
library(tidyverse)
# Create a city_state variable
homicide_df = read.csv("./homicide-data.csv")|>
 mutate(city_state = paste(city, state, sep = ", "))

#summarize within cities to obtain the total number of homicides and the number of unsolved homicides 
homicide_df1=homicide_df |>
  group_by (city) |>
  summarize(total_homicides=n(),
            unsolved_homicides=sum(disposition %in% c("Closed without arrest","Closed by arrest")))
homicide_df1
```

For the city of Baltimore, MD, use the prop.test function to estimate the proportion of homicides that are unsolved; save the output of prop.test as an R object, apply the broom::tidy to this object and pull the estimated proportion and confidence intervals from the resulting tidy dataframe.

```{r}
baltimore_homicides <- homicide_df %>%
  filter(city == "Baltimore", state == "MD")

# Use prop.test to estimate the proportion of unsolved homicides
unsolved_homicides <- sum(baltimore_homicides$disposition %in% c("Closed without arrest", "Open/No arrest"))
total_homicides <- nrow(baltimore_homicides)

prop_test_result <- prop.test(unsolved_homicides, total_homicides)

# Tidy the result of prop.test using broom::tidy
tidy_prop_test <- broom::tidy(prop_test_result)

# Pull the estimate and confidence intervals
tidy_estimate_ci <- tidy_prop_test %>%
  select(estimate, conf.low, conf.high) %>%
  pull()
```

```{r}

# Create a summary dataframe with counts of unsolved and total homicides by city
city_summary <- homicide_df %>%
  group_by(city, state) %>%
  summarise(
    unsolved_homicides = sum(disposition %in% c("Closed without arrest", "Open/No arrest")),
    total_homicides = n(),
    .groups = "drop"
  )

# Use purrr to apply prop.test to each city and tidy the results
tidy_prop_test_results <- city_summary %>%
  mutate(
    prop_test = map2(unsolved_homicides, total_homicides, ~prop.test(.x, .y)),
    tidy_results = map(prop_test, broom::tidy)
  ) %>%
  select(city, state, tidy_results) %>%
  unnest(tidy_results)
tidy_proportions_ci <- tidy_prop_test_results %>%
  select(city, state, estimate, conf.low, conf.high)
tidy_proportions_ci
```

```{r}
tidy_proportions_ci <- tidy_proportions_ci %>%
  arrange(desc(estimate))
plot <- ggplot(tidy_proportions_ci, aes(x = reorder(city, estimate), y = estimate)) +
  geom_point() +
  geom_errorbar(aes(ymin = conf.low, ymax = conf.high), width = 0.2) +
  coord_flip() +  # Flip the axes to make the plot horizontal
  labs(x = "City", y = "Proportion of Unsolved Homicides", title = "Proportion of Unsolved Homicides by City") +
  theme_minimal()

ggsave(filename = "unsolved_homicides_by_city.png", plot = plot, width = 10, height = 8, dpi = 300)
```





